Repository depromeet/ggogeet-client, pull requests merged in 2022-11, with the labels that each got.

#1 Create PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#2 ✨ Feat : 임시 api 호출 구조 추가
  src/apis/api/users.ts
  src/apis/axiosInstance/axios.ts
  src/apis/models/Auth.ts
  src/apis/models/BaseModel.ts
  src/apis/requester.ts
  src/apis/responses/BaseResponse.ts
  src/apis/types/index.d.ts
  src/constants/api.ts
  src/utils/cookies.ts
Labels: 📬 API

#9 💄 스타일 기본 세팅 추가
  src/pages/_app.tsx
  src/styles/commons.ts
  src/styles/global.css
  src/styles/global.ts
  src/styles/theme.ts
  src/types/theme.d.ts
Labels: 🎨 Html&css

#14 ✨ tag 공통 컴포넌트 추가
  src/components/common/Tag/index.tsx
  src/components/common/Tag/styled.ts
Labels: ✨ Feature, 🎨 Html&css

#15 📝 버그 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/버그-템플릿-.md
Labels: 📃 Docs

#16 📝 기능 개발 이슈 템플릿 생성
  .github/ISSUE_TEMPLATE/기능-템플릿-.md
Labels: 📃 Docs

#18 📝 pr 템플릿 이슈번호 항목 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs

#19 BottomButton 공통 컴포넌트 추가
  src/components/common/Buttons/BottomButton/index.tsx
  src/components/common/Buttons/BottomButton/styled.ts
Labels: ✨ Feature, 🎨 Html&css

#26 ✨ tag 공통 컴포넌트 설계 변경
  src/components/common/Buttons/TagButton/index.tsx
  src/components/common/Buttons/TagButton/styled.ts
  src/components/common/Tag/index.tsx
  src/components/common/Tag/styled.ts
Labels: ✨ Feature, 🎨 Html&css

#10 ✨ Feat: Main Page - GNB component
  public/icons/nav-bell.svg
  public/icons/nav-logo.svg
  src/assets/styles/index.ts
  src/components/common/gnb/GNB.style.ts
  src/components/common/gnb/GNB.tsx
  src/components/common/gnb/NavBell.tsx
  src/components/common/gnb/NavLogo.tsx
  src/components/common/gnb/index.ts
  src/components/domain/main/index.ts
  src/pages/index.tsx
Labels: ✨ Feature
