Repository depromeet/ggogeet-client, pull requests merged in 2022-12, with the labels that each got.

#30 ✨ CircleButton 공통 컴포넌트 추가
  src/components/common/Buttons/CircleButton/index.tsx
  src/components/common/Buttons/CircleButton/styled.ts
Labels: ✨ Feature, 🎨 Html&css

#37 ✨ select 컴포넌트 추가
  src/components/common/Select/index.tsx
  src/components/common/Select/styled.ts
  src/stories/Select.stories.tsx
Labels: ✨ Feature, 🎨 Html&css

#41 🐛 feature/letter-write merge 에러 수정 및 폴더명 파스칼 케이스로 변경
  src/components/common/TopNavigation/atoms/NavBack.tsx
  src/components/common/TopNavigation/atoms/NavBell.tsx
  src/components/common/TopNavigation/atoms/NavLogo.tsx
  src/components/common/TopNavigation/atoms/NavMenu.tsx
  src/components/common/gnb/index.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverNameForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/RelationshipForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/index.ts
  src/components/features/LetterWrite/InputRecipient/Layout/index.tsx
  src/components/features/LetterWrite/InputRecipient/styled.ts
  src/components/features/LetterWrite/common/TagContainer/index.tsx
  src/components/features/LetterWrite/common/TagContainer/styled.ts
  src/components/features/LetterWrite/common/index.ts
  src/components/features/LetterWrite/main/TextEditor/CustomTextEditorToolbar/index.tsx
  src/components/features/LetterWrite/main/TextEditor/CustomTextEditorToolbar/styled.ts
  src/components/features/LetterWrite/main/TextEditor/index.tsx
  src/components/features/LetterWrite/main/TextEditor/styled.ts
  src/components/features/LetterWrite/main/TextTip/index.tsx
  src/components/features/LetterWrite/main/TextTip/styled.ts
  src/components/features/LetterWrite/main/Toolbar/index.tsx
  src/components/features/LetterWrite/main/Toolbar/styled.ts
  src/components/features/LetterWrite/main/index.tsx
  src/pages/LetterWrite/index.tsx
  src/pages/index.tsx
  src/utils/helper/LetterWrite.ts
Labels: 🐞 BugFix

#46 🍱 prettier 설정 및 폰트 추가
  .pnp.cjs
  .pnp.loader.mjs
  .prettierrc
  src/pages/_document.tsx
  src/styles/commons.ts
  src/styles/global.ts
Labels: ✨ Feature

#35 ✨ letter-remind 페이지 레이아웃, 관련 컴포넌트 생성
  public/icons/bell.svg
  public/icons/smallDownArrow.svg
  public/icons/smallUpArrow.svg
  src/components/common/Buttons/ToggleArrowButton/index.tsx
  src/components/common/Buttons/ToggleArrowButton/styled.ts
  src/components/features/letter-remind/TodoContainer/index.tsx
  src/components/features/letter-remind/TodoContainer/styled.ts
  src/pages/letter-remind/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#42 💄 편지 작성 - 관계 설정 스크린 UI 추가
  src/components/common/Buttons/BottomButton/styled.ts
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverNameForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/RelationshipForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/SituationForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/index.ts
  src/components/features/LetterWrite/InputRecipient/Hooks/index.ts
  src/components/features/LetterWrite/InputRecipient/Hooks/useBottomButton.tsx
  src/components/features/LetterWrite/InputRecipient/styled.ts
  src/components/features/LetterWrite/common/TagContainer/index.tsx
  src/data/LetterWrite/index.ts
  src/data/LetterWrite/type.d.ts
  src/pages/letter-write/index.tsx
  src/utils/LetterWrite.ts
  src/utils/helper/index.ts
Labels: 🎨 Html&css

#55 💄 grayScale 추가
  src/styles/theme.ts
  src/types/theme.d.ts
Labels: 🎨 Html&css

#39 💄 letter-remind/write 페이지 UI 구현
  public/icons/backArrow.svg
  src/components/common/Buttons/ToggleArrowButton/index.tsx
  src/components/common/Buttons/ToggleArrowButton/styled.ts
  src/data/LetterRemind/index.ts
  src/pages/letter-remind/index.tsx
  src/pages/letter-remind/write.tsx
  src/styles/global.ts
Labels: 🎨 Html&css

#48 💄 letter-storage 페이지 UI 개발
  src/components/features/letter-remind/TodoContainer/index.tsx
  src/components/features/letter-remind/TodoContainer/styled.ts
  src/components/features/letter-storage/LetterContainer/index.tsx
  src/components/features/letter-storage/LetterContainer/styled.ts
  src/components/features/letter-storage/LetterStorageTopNavigation/index.tsx
  src/components/features/letter-storage/LetterStorageTopNavigation/styled.ts
  src/pages/letter-storage/index.tsx
Labels: 🎨 Html&css

#59 ✨ Textarea 컴포넌트 추가
  .storybook/preview-head.html
  .storybook/preview.js
  src/components/common/Input/styled.ts
  src/components/common/Textarea/index.tsx
  src/components/common/Textarea/styled.ts
  src/stories/Textarea.stories.tsx
  src/styles/global.ts
Labels: ✨ Feature, 🎨 Html&css

#53 💄 공통 컴포넌트 설계 수정
  src/components/common/Buttons/BottomButton/styled.ts
  src/components/common/TopNavigation/index.tsx
  src/components/common/TopNavigation/styled.ts
Labels: 🎨 Html&css

#64 💄 letter-remind 페이지 상세 UI 개발
  public/icons/hamburger.svg
  src/components/features/letter-remind/TodoContainer/index.tsx
  src/components/features/letter-remind/TodoContainer/styled.ts
  src/data/LetterRemind/index.ts
  src/pages/letter-remind/index.tsx
Labels: 🎨 Html&css

#67 ✨ Checkbox 공통 컴포넌트 개발
  public/icons/check_ico.svg
  src/components/common/Buttons/Checkbox/index.tsx
  src/components/common/Buttons/Checkbox/styled.ts
Labels: ✨ Feature, 🎨 Html&css

#71 💄 Button 공통 컴포넌트 수정
  src/components/common/Buttons/Button/index.tsx
  src/components/common/Buttons/Button/styled.ts
  src/components/common/Buttons/Button/types.d.ts
  src/styles/commons.ts
Labels: ✨ Feature, 🎨 Html&css

#72 💄 공통 컴포넌트 수정
  src/components/common/TopNavigation/styled.ts
  src/styles/global.ts
Labels: ✨ Feature, 🎨 Html&css

#75 💄 편지 작성 - 가이드라인/리마인드 바텀시트 UI 및 전반적인 스타일 리팩토링
  public/icons/icon__accordion-bell.svg
  public/icons/icon__accordion-chevron-down.svg
  public/icons/icon__guideline-close--gray.svg
  public/icons/icon__guideline-close--white.svg
  public/icons/icon__guideline-plus.svg
  public/icons/icon__guideline-tag.svg
  public/icons/icon__home-help.svg
  public/icons/icon__home-setting.svg
  src/components/common/Buttons/BottomButton/styled.ts
  src/components/common/Buttons/Button/styled.ts
  src/components/common/Input/InputDefault.tsx
  src/components/common/Input/styled.ts
  src/components/common/Select/styled.ts
  src/components/common/Textarea/styled.ts
  src/components/common/TopNavigation/atoms/NavBack.tsx
  src/components/common/TopNavigation/atoms/NavBell.tsx
  src/components/common/TopNavigation/atoms/NavLogo.tsx
  src/components/common/TopNavigation/atoms/NavMenu.tsx
  src/components/common/TopNavigation/atoms/styled.ts
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverNameForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/RelationshipForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/SituationForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/index.ts
  src/components/features/LetterWrite/InputRecipient/Hooks/useBottomButton.tsx
  src/components/features/LetterWrite/InputRecipient/styled.ts
  src/components/features/LetterWrite/common/Accordion/index.tsx
  src/components/features/LetterWrite/common/TagContainer/index.tsx
  src/components/features/LetterWrite/common/styled.ts
  src/components/features/LetterWrite/main/Guideline/index.tsx
  src/components/features/LetterWrite/main/Remind/index.tsx
  src/components/features/LetterWrite/main/TextEditor/CustomTextEditorToolbar/index.tsx
  src/components/features/LetterWrite/main/TextEditor/index.tsx
  src/components/features/LetterWrite/main/TextTip/index.tsx
  src/components/features/LetterWrite/main/Toolbar/index.tsx
  src/components/features/LetterWrite/main/index.tsx
  src/components/features/LetterWrite/main/styled.ts
  src/components/features/letter-remind/TodoContainer/styled.ts
  src/data/LetterWrite/index.ts
  src/data/LetterWrite/type.d.ts
  src/store/LetterWrite.ts
  src/styles/global.ts
  src/types/Letter.d.ts
Labels: ✨ Feature, 🎨 Html&css, 🔨 Refactor

#78 💄 편지 작성 - 친구 목록 UI
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverFriendsForm.tsx
  src/components/features/LetterWrite/InputRecipient/styled.ts
  src/data/LetterWrite/index.ts
  src/types/Letter.d.ts
Labels: 🎨 Html&css

#69 💄 letter-remind/write 페이지 상세 UI 개발
  src/components/common/Buttons/TagButton/index.tsx
  src/components/common/TagsContainer/index.tsx
  src/components/common/TagsContainer/styled.ts
  src/pages/letter-remind/write.tsx
Labels: ✨ Feature, 🎨 Html&css

#73 💄 letter-storage 페이지 바텀시트
  public/icons/reload.svg
  src/components/common/BottomSheet/index.tsx
  src/components/features/letterRemind/TodoContainer/index.tsx
  src/components/features/letterRemind/TodoContainer/styled.ts
  src/components/features/letterStorage/bottomSheet/BottomSheetFooter/index.tsx
  src/components/features/letterStorage/bottomSheet/BottomSheetFooter/styled.ts
  src/components/features/letterStorage/bottomSheet/BottomSheetHeader/index.tsx
  src/components/features/letterStorage/bottomSheet/BottomSheetHeader/styled.ts
  src/components/features/letterStorage/bottomSheet/InitializationButton/index.tsx
  src/components/features/letterStorage/bottomSheet/InitializationButton/styled.ts
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/index.tsx
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/styled.ts
  src/components/features/letterStorage/bottomSheet/ListContainer/index.tsx
  src/components/features/letterStorage/bottomSheet/ListContainer/styled.ts
  src/components/features/letterStorage/main/LetterContainer/index.tsx
  src/components/features/letterStorage/main/LetterContainer/styled.ts
  src/components/features/letterStorage/main/LetterStorageTopNavigation/index.tsx
  src/components/features/letterStorage/main/LetterStorageTopNavigation/styled.ts
  src/data/LetterStorage/index.ts
  src/pages/letter-remind/index.tsx
  src/pages/letter-storage/index.tsx
Labels: ✨ Feature, 🎨 Html&css, 🙋‍♂️ Question

#92 💄 Checkbox 컴포넌트 수정
  public/icons/check_ico.svg
  src/components/common/Buttons/Checkbox/index.tsx
  src/components/common/Buttons/Checkbox/styled.ts
Labels: 🎨 Html&css

#79 💄 편지 작성 - 상황 UI
  .pnp.cjs
  .yarn/cache/@types-react-slick-npm-0.23.10-7a4823c988-1e53fe8385.zip
  .yarn/cache/classnames-npm-2.3.2-d2fdae468d-2c62199789.zip
  .yarn/cache/enquire.js-npm-2.1.6-fc4ea2e583-bb094054ee.zip
  .yarn/cache/json2mq-npm-0.2.0-aa8a6516b9-5672c3abdd.zip
  .yarn/cache/react-slick-npm-0.29.0-28db290b04-67ce498191.zip
  .yarn/cache/resize-observer-polyfill-npm-1.5.1-603120e8a0-57e7f79489.zip
  .yarn/cache/slick-carousel-npm-1.8.1-8382d373c2-acaad391e4.zip
  .yarn/cache/string-convert-npm-0.2.1-f1a42cb9ea-1098b1d8e3.zip
  package.json
  src/components/features/LetterWrite/Common/CustomSlider/index.tsx
  src/components/features/LetterWrite/Common/SituationTag/index.tsx
  src/components/features/LetterWrite/Common/styled.ts
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverNameForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/SituationForm.tsx
  src/components/features/LetterWrite/InputRecipient/styled.ts
  src/data/LetterWrite/index.ts
  src/data/LetterWrite/type.d.ts
  yarn.lock
Labels: ✨ Feature, 🎨 Html&css
