Repository depromeet/ggogeet-client, pull requests merged in 2023-01, with the labels that each got.

#84 💄 편지 작성 - 완료 UI
  public/icons/icon__kakao-talk.png
  public/images/image__completed-progress.svg
  public/images/image__completed-template01.png
  public/images/image__completed-template02.png
  public/images/image__completed-template03.png
  public/images/image__completed-template04.png
  public/images/image__completed-template05.png
  public/images/image__completed-template06.png
  public/images/image__completed-template07.png
  public/images/image__completed-template08.png
  public/images/image__situation-template01.png
  public/images/image__situation-template02.png
  public/images/image__situation-template03.png
  public/images/image__situation-template04.png
  public/images/image__situation-template05.png
  public/images/image__situation-template06.png
  public/images/image__situation-template07.png
  public/images/image__situation-template08.png
  src/components/common/Select/styled.ts
  src/components/features/Home/index.tsx
  src/components/features/Home/styled.ts
  src/components/features/LetterWrite/Common/CustomSlider/index.tsx
  src/components/features/LetterWrite/Common/styled.ts
  src/components/features/LetterWrite/InputRecipient/Forms/CompletedForm01.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/CompletedForm02.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverFriendsForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverNameForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/SituationForm.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/index.ts
  src/components/features/LetterWrite/InputRecipient/Hooks/index.ts
  src/components/features/LetterWrite/InputRecipient/Hooks/useBottomButton.tsx
  src/components/features/LetterWrite/InputRecipient/Hooks/useTextLengthPixel.tsx
  src/components/features/LetterWrite/InputRecipient/Loadings/LetterCompletedProgress.tsx
  src/components/features/LetterWrite/InputRecipient/Loadings/index.ts
  src/components/features/LetterWrite/InputRecipient/styled.ts
  src/components/features/LetterWrite/Main/Guideline/index.tsx
  src/components/features/LetterWrite/Main/Layout/index.tsx
  src/components/features/LetterWrite/Main/TextEditor/index.tsx
  src/components/features/LetterWrite/Main/styled.ts
  src/components/features/letterRemind/TodoContainer/styled.ts
  src/components/features/letterStorage/bottomSheet/ListContainer/styled.ts
  src/data/LetterWrite/index.ts
  src/data/LetterWrite/type.d.ts
  src/pages/letter-write/index.tsx
  src/store/LetterWrite.ts
  src/styles/commons.ts
  src/utils/LetterWrite.ts
  src/utils/date.ts
Labels: ✨ Feature, 🎨 Html&css

#101 ✨ 로그인 API 연동 및 저장 추가
  .pnp.cjs
  .yarn/cache/@types-cookie-npm-0.4.1-274a704dc6-3275534ed6.zip
  .yarn/cache/cookie-npm-0.4.2-7761894d5f-a00833c998.zip
  .yarn/cache/cookies-next-npm-2.1.1-b220fa0499-c5fc2c72cf.zip
  .yarn/cache/decode-uri-component-npm-0.4.1-61db093ef6-0473924860.zip
  .yarn/cache/filter-obj-npm-5.1.0-a1ae61a7db-ba7c24d9b2.zip
  .yarn/cache/query-string-npm-8.1.0-e74248e410-16fe49ab71.zip
  .yarn/cache/split-on-first-npm-3.0.0-3b993e48ae-75dc27ecba.zip
  package.json
  src/apis/auth.ts
  src/apis/requester.ts
  src/components/features/signin/Content/index.tsx
  src/constants/keys.ts
  src/hooks/index.ts
  src/hooks/useAuth.ts
  src/hooks/useOauth.ts
  src/pages/_app.tsx
  src/pages/api/redirect/kakao/index.tsx
  src/pages/signin/index.tsx
  src/pages/signin/redirect/kakao.tsx
  yarn.lock
Labels: 📬 API

#82 💄 받은 편지 추가 페이지 UI
  src/components/features/letterStorage/add/AddImage/index.tsx
  src/components/features/letterStorage/add/AddImage/styled.ts
  src/components/features/letterStorage/add/AddNavigationBar/index.tsx
  src/components/features/letterStorage/add/AddNavigationBar/styled.ts
  src/components/features/letterStorage/add/AddText/index.tsx
  src/components/features/letterStorage/add/AddText/styled.ts
  src/components/features/letterStorage/bottomSheet/BottomSheetFooter/index.tsx
  src/components/features/letterStorage/bottomSheet/BottomSheetHeader/index.tsx
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/index.tsx
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/styled.ts
  src/components/features/letterStorage/bottomSheet/ListContainer/index.tsx
  src/components/features/letterStorage/bottomSheet/ListContainer/styled.ts
  src/pages/letter-storage/add.tsx
  src/pages/letter-storage/index.tsx
  src/pages/letter-storage/reply.tsx
Labels: ✨ Feature, 🎨 Html&css, 🙋‍♂️ Question

#86 💄 꼬깃 메모 페이지 UI
  next.config.js
  public/icons/pencil.svg
  public/icons/trashCan.svg
  public/icons/yellowBell.svg
  src/components/features/letter-remind/Main/DeleteButton/index.tsx
  src/components/features/letter-remind/Main/DeleteButton/styled.ts
  src/components/features/letter-remind/Main/EditButton/index.tsx
  src/components/features/letter-remind/Main/EditButton/styled.ts
  src/components/features/letter-remind/Main/RemindNavigationBar/index.tsx
  src/components/features/letter-remind/Main/RemindNavigationBar/styled.ts
  src/components/features/letter-remind/Main/TodoContainer/index.tsx
  src/components/features/letter-remind/Main/TodoContainer/styled.ts
  src/components/features/letter-remind/Main/TodoContainerList/index.tsx
  src/components/features/letter-remind/Main/TodoContainerList/styled.ts
  src/data/LetterRemind/index.ts
  src/pages/letter-remind/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#88 💄 꼬깃 메모 추가 페이지 UI
  src/components/common/TagsContainer/index.tsx
  src/components/common/TagsContainer/styled.ts
  src/pages/letter-remind/write.tsx
Labels: 🎨 Html&css

#91 💄 꼬깃 보관함 UI
  public/icons/closeQuote.svg
  public/icons/filter.svg
  public/icons/openQuote.svg
  public/icons/plus.svg
  public/icons/sort.svg
  src/components/features/letter-storage/FilterButton/index.tsx
  src/components/features/letter-storage/FilterButton/styled.ts
  src/components/features/letter-storage/PlusButton/index.tsx
  src/components/features/letter-storage/PlusButton/styled.ts
  src/components/features/letter-storage/SortButton/index.tsx
  src/components/features/letter-storage/SortButton/styled.ts
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/index.tsx
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/styled.ts
  src/components/features/letterStorage/bottomSheet/ListContainer/index.tsx
  src/components/features/letterStorage/bottomSheet/ListContainer/styled.ts
  src/components/features/letterStorage/main/LetterContainer/index.tsx
  src/components/features/letterStorage/main/LetterContainer/styled.ts
  src/pages/letter-remind/index.tsx
  src/pages/letter-storage/index.tsx
Labels: 🎨 Html&css

#105 ✨ error-boundary 임시 추가
  .pnp.cjs
  .yarn/cache/react-error-boundary-npm-3.1.4-2310dba89e-f36270a5d7.zip
  package.json
  src/pages/_app.tsx
  yarn.lock
Labels: ✨ Feature

#106 ✨ Create Calendar
  .pnp.cjs
  .yarn/cache/@types-history-npm-4.7.11-fe05d7b2e1-c92e2ba407.zip
  .yarn/cache/@types-react-calendar-npm-3.9.0-d2fc83b98e-cddb6951c2.zip
  .yarn/cache/@types-react-router-npm-5.1.20-620ccce99a-1287641434.zip
  .yarn/cache/@wojtekmaj-date-utils-npm-1.0.3-66943d4ae0-70b7152160.zip
  .yarn/cache/get-user-locale-npm-1.5.1-4cba510c56-4ab9ae8326.zip
  .yarn/cache/lodash.memoize-npm-4.1.2-0e6250041f-9ff3942fee.zip
  .yarn/cache/react-calendar-npm-4.0.0-8f03cd673a-a470ea1eab.zip
  package.json
  src/components/features/letterRemind/Main/DeleteButton/index.tsx
  src/components/features/letterRemind/Main/DeleteButton/styled.ts
  src/components/features/letterRemind/Main/EditButton/index.tsx
  src/components/features/letterRemind/Main/EditButton/styled.ts
  src/components/features/letterRemind/Main/RemindNavigationBar/index.tsx
  src/components/features/letterRemind/Main/RemindNavigationBar/styled.ts
  src/components/features/letterRemind/Main/TodoContainer/index.tsx
  src/components/features/letterRemind/Main/TodoContainer/styled.ts
  src/components/features/letterRemind/Main/TodoContainerList/index.tsx
  src/components/features/letterRemind/Main/TodoContainerList/styled.ts
  src/components/features/letterRemind/TodoContainer/index.tsx
  src/components/features/letterRemind/TodoContainer/styled.ts
  src/components/features/letterStorage/bottomSheet/BottomSheetHeader/index.tsx
  src/components/features/letterStorage/bottomSheet/CalendarBottomSheet/index.tsx
  src/components/features/letterStorage/bottomSheet/CalendarBottomSheet/styled.ts
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/index.tsx
  src/components/features/letterStorage/bottomSheet/ListContainer/styled.ts
  src/components/features/letterStorage/main/FilterButton/index.tsx
  src/components/features/letterStorage/main/FilterButton/styled.ts
  src/components/features/letterStorage/main/LetterContainer/index.tsx
  src/components/features/letterStorage/main/PlusButton/index.tsx
  src/components/features/letterStorage/main/PlusButton/styled.ts
  src/components/features/letterStorage/main/SortButton/index.tsx
  src/components/features/letterStorage/main/SortButton/styled.ts
  src/pages/letter-remind/index.tsx
  src/pages/letter-storage/index.tsx
  yarn.lock
Labels: ✨ Feature, 🐞 BugFix, 🙋‍♂️ Question

#108 💄 letter-reply 페이지
  src/pages/letter-reply/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#104 ✨ 편지 작성 API 연동 작업 02
  public/images/image__empty.svg
  src/apis/auth.ts
  src/apis/letter.ts
  src/apis/reminder.ts
  src/apis/users.ts
  src/components/features/LetterWrite/Common/Accordion/index.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/CompletedForm01.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/CompletedForm02.tsx
  src/components/features/LetterWrite/InputRecipient/Forms/ReceiverFriendsForm.tsx
  src/components/features/LetterWrite/Main/Remind/index.tsx
  src/components/features/LetterWrite/Main/styled.ts
  src/constants/api.ts
  src/hooks/useInterval.ts
  src/react-query/constants.ts
  src/types/auth.d.ts
  src/types/letter.d.ts
  src/types/reminder.d.ts
  src/types/users.d.ts
Labels: 📬 API

#116 ✨ 리마인드 페이지 API
  src/apis/reminder.ts
  src/components/features/letterRemind/Main/LetterAddButton/index.tsx
  src/components/features/letterRemind/Main/LetterAddButton/styled.ts
  src/components/features/letterRemind/Main/RemindNavigationBar/index.tsx
  src/components/features/letterRemind/Main/TodoContainer/index.tsx
  src/components/features/letterRemind/Main/TodoContainerList/index.tsx
  src/components/features/letterRemind/Write/TagsContainer/index.tsx
  src/components/features/letterRemind/Write/TagsContainer/styled.ts
  src/data/LetterRemind/index.ts
  src/pages/letter-remind/index.tsx
  src/pages/letter-remind/write.tsx
  src/store/LetterRemind.ts
Labels: ✨ Feature, 🎨 Html&css, 📬 API

#120 ✨ 메모 삭제 추가
  src/apis/reminder.ts
  src/components/features/letterRemind/Main/DeleteButton/index.tsx
  src/components/features/letterRemind/Main/DeleteButton/styled.ts
  src/components/features/letterRemind/Main/TodoContainer/index.tsx
  src/components/features/letterRemind/Main/TodoContainer/styled.ts
  src/components/features/letterRemind/Main/TodoContainerList/index.tsx
  src/pages/letter-remind/index.tsx
Labels: 📬 API

#122 💄 너비 설정
  src/styles/global.ts
Labels: ✨ Feature

#118 💄 편지 보관함 UI 수정
  src/components/features/letterStorage/main/FilterButton/index.tsx
  src/components/features/letterStorage/main/LetterContainer/index.tsx
  src/components/features/letterStorage/main/SortButton/index.tsx
  src/pages/letter-storage/index.tsx
Labels: ✨ Feature, 🎨 Html&css

#133 ✨ 편지 보관함 API
  src/apis/letter.ts
  src/components/features/letterStorage/bottomSheet/BottomSheetFooter/index.tsx
  src/components/features/letterStorage/bottomSheet/BottomSheetHeader/index.tsx
  src/components/features/letterStorage/bottomSheet/InitializationButton/index.tsx
  src/components/features/letterStorage/bottomSheet/ListBottomSheet/index.tsx
  src/components/features/letterStorage/bottomSheet/ListContainer/index.tsx
  src/components/features/letterStorage/bottomSheet/ListContainer/styled.ts
  src/components/features/letterStorage/main/LetterContainer/index.tsx
  src/pages/letter-storage/index.tsx
  src/types/letter.d.ts
Labels: ✨ Feature, 📬 API

#126 ✨ 편지 상세 조회 기능 임시 추가
  src/apis/letter.ts
  src/pages/letter-reply/index.tsx
  src/react-query/constants.ts
  src/types/letter.d.ts
Labels: ✨ Feature

#135 ✨ 꼬깃 보관함 상세페이지 수정
  src/pages/letter-reply/index.tsx
  src/pages/letter-storage/reply.tsx
  src/types/letter.d.ts
Labels: ✨ Feature, 📬 API
